development:
    adapter: mysql
    database: hobocookbook_development
    encoding: utf8
    
test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  adapter: mysql
  database: hobocookbook_production
  encoding: utf8
